//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Families = new HashSet<Family>();
            this.Shares = new HashSet<Share>();
        }
    
        public int Id { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<short> HouseNumber { get; set; }
        public int Address_Street { get; set; }
    
        public virtual Street Street { get; set; }
        public virtual ICollection<Family> Families { get; set; }
        public virtual ICollection<Share> Shares { get; set; }
    }
}
