//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public System.DateTime date { get; set; }
        public string message { get; set; }
        public Nullable<int> personId { get; set; }
        public int Id { get; set; }
    }
}
