//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public Family()
        {
            this.People = new HashSet<Person>();
            this.PoolAccesses = new HashSet<PoolAccess>();
            this.ShareFamilies = new HashSet<ShareFamily>();
        }
    
        public int Id { get; set; }
        public string FamilyName { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string Email { get; set; }
        public string PrimaryPhone { get; set; }
        public Nullable<int> Family_Address { get; set; }
        public Nullable<int> Family_ShareUserType { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ShareUserType ShareUserType { get; set; }
        public virtual ICollection<PoolAccess> PoolAccesses { get; set; }
        public virtual ICollection<ShareFamily> ShareFamilies { get; set; }
    }
}
