//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hourlycount
    {
        public long Row { get; set; }
        public System.DateTime entry_date { get; set; }
        public Nullable<int> hour_slot { get; set; }
        public Nullable<int> entry_count { get; set; }
    }
}
