//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> Sent { get; set; }
        public Nullable<System.DateTime> Read { get; set; }
        public string From { get; set; }
        public string ReplyPhone { get; set; }
        public string ReplyEmail { get; set; }
        public string Display { get; set; }
        public Nullable<int> Message_Family { get; set; }
        public Nullable<int> Message_Person { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Person Person { get; set; }
    }
}
