//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoolDataEntitiesConnection : DbContext
    {
        public PoolDataEntitiesConnection()
            : base("name=PoolDataEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Entry> Entries { get; set; }
        public DbSet<Family> Families { get; set; }
        public DbSet<FamilyMemberType> FamilyMemberTypes { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PoolAccess> PoolAccesses { get; set; }
        public DbSet<ShareFamily> ShareFamilies { get; set; }
        public DbSet<ShareOwnerType> ShareOwnerTypes { get; set; }
        public DbSet<Share> Shares { get; set; }
        public DbSet<ShareUserType> ShareUserTypes { get; set; }
        public DbSet<Street> Streets { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeTime> EmployeeTimes { get; set; }
        public DbSet<vw_aspnet_MembershipUsers> vw_aspnet_MembershipUsers { get; set; }
        public DbSet<hourlycount> hourlycounts { get; set; }
        public DbSet<rpt_employee_time> rpt_employee_time { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
    }
}
