//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoolAccess
    {
        public int Id { get; set; }
        public int PoolAccess_Share { get; set; }
        public Nullable<int> PoolAccess_ShareOwnerType { get; set; }
        public Nullable<int> PoolAccess_ShareUserType { get; set; }
        public int PoolAccess_Family { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual ShareOwnerType ShareOwnerType { get; set; }
        public virtual ShareUserType ShareUserType { get; set; }
    }
}
