//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_employee_time
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeType { get; set; }
        public string in_out { get; set; }
        public string date_time { get; set; }
    }
}
