//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareFamily
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public int ShareFamily_Share { get; set; }
        public int ShareFamily_Family { get; set; }
        public int ShareFamily_ShareUserType { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Share Share { get; set; }
        public virtual ShareUserType ShareUserType { get; set; }
    }
}
