//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPoolCheckin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public Share()
        {
            this.ShareFamilies = new HashSet<ShareFamily>();
        }
    
        public int Id { get; set; }
        public string Notes { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Share_Address { get; set; }
        public bool Paid_Dues { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<ShareFamily> ShareFamilies { get; set; }
    }
}
